// AUTO-GENERATED by scripts/build_catalogue.py — do not edit by hand.
// Canonical Term V course list. The image parser matches against course
// CODES from this list, which is exact-match rather than fuzzy guessing.

export interface CatalogueCourse {
  code: string;
  name: string;
  phase: 'full' | 'pre_mid' | 'post_mid';
  /** 3 credits = 20 classes at 75%; 1.5 credits = 10 classes at 80%. */
  credits: number;
  total_classes: number;
  min_pct: number;
  /** 'weekly' repeats; 'dates' runs on the fixed list in each meeting. */
  schedule_type?: 'weekly' | 'dates';
  sections: Record<string, {
    day: number; start: string; end: string; date?: string;
  }[]>;
}

export const TERM = "TERM-V: AY 2026-2027";

export const CATALOGUE: CatalogueCourse[] = [
  {
    "code": "AP",
    "name": "Analytics in Practice",
    "phase": "pre_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "L-51",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 2,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "BM",
    "name": "Bank Management",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "dates",
    "sections": {
      "A": [
        {
          "date": "2026-09-01",
          "day": 2,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-01",
          "day": 2,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-02",
          "day": 3,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-09-02",
          "day": 3,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-09-08",
          "day": 2,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-08",
          "day": 2,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-09",
          "day": 3,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-09-09",
          "day": 3,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-09-15",
          "day": 2,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-15",
          "day": 2,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-16",
          "day": 3,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-09-16",
          "day": 3,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-11-03",
          "day": 2,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-11-03",
          "day": 2,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-04",
          "day": 3,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-04",
          "day": 3,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-11-17",
          "day": 2,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-11-17",
          "day": 2,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-18",
          "day": 3,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-18",
          "day": 3,
          "start": "12:00",
          "end": "13:30"
        }
      ]
    },
    "official_code": "FI-242"
  },
  {
    "code": "CB",
    "name": "Consumer Behaviour",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "N-22",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 3,
          "start": "18:00",
          "end": "19:15"
        }
      ]
    }
  },
  {
    "code": "CCM",
    "name": "Consumption Culture & Markets",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-4",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "CRA",
    "name": "Country Risk Analysis",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 3,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "CMLSE",
    "name": "Creating, Managing, and Leading Social Enterprises",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-4",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 3,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "DTDPS",
    "name": "Design Thinking for Digital Products and Services",
    "phase": "post_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "Tata Hall (East-West Conference room)",
    "schedule_type": "dates",
    "sections": {
      "A": [
        {
          "date": "2026-10-31",
          "day": 6,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-10-31",
          "day": 6,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-01",
          "day": 7,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-01",
          "day": 7,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-11-14",
          "day": 6,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-15",
          "day": 7,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-15",
          "day": 7,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-11-21",
          "day": 6,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-22",
          "day": 7,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-22",
          "day": 7,
          "start": "12:00",
          "end": "13:30"
        }
      ]
    },
    "official_code": "MI-300"
  },
  {
    "code": "EVIB",
    "name": "Ethics and Values in International Business",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "N-22",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 3,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "FRM",
    "name": "Financial Risk Management",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "dates",
    "sections": {
      "A": [
        {
          "date": "2026-08-28",
          "day": 5,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-08-28",
          "day": 5,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-08-29",
          "day": 6,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-08-29",
          "day": 6,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-09-04",
          "day": 5,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-04",
          "day": 5,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-05",
          "day": 6,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-09-05",
          "day": 6,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-09-18",
          "day": 5,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-18",
          "day": 5,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-19",
          "day": 6,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-09-19",
          "day": 6,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-11-13",
          "day": 5,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-11-13",
          "day": 5,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-14",
          "day": 6,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-14",
          "day": 6,
          "start": "12:00",
          "end": "13:30"
        },
        {
          "date": "2026-11-20",
          "day": 5,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-11-20",
          "day": 5,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-21",
          "day": 6,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-21",
          "day": 6,
          "start": "12:00",
          "end": "13:30"
        }
      ]
    },
    "official_code": "FI-283"
  },
  {
    "code": "FIM",
    "name": "Fixed Income Markets",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-4",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "IASP",
    "name": "Industry Analysis, Strategy and Performance",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-4",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "ISTPCM",
    "name": "Inside Storytelling - Theories and Praxis for Communication and Management",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (East-150)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 6,
          "start": "10:15",
          "end": "11:30"
        }
      ],
      "B": [
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 6,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "IMC",
    "name": "Integrated Marketing Communication",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (East-150)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "LSCM",
    "name": "Logistics and Supply Chain Management",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "N-22",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 2,
          "start": "18:00",
          "end": "19:15"
        }
      ],
      "B": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MSO",
    "name": "Management of Self in Organisations",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-51",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 4,
          "start": "18:00",
          "end": "19:15"
        }
      ]
    }
  },
  {
    "code": "MEIIP",
    "name": "Managerial Excellence: Insights from Indian Philosophy",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "N-22",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "MDT",
    "name": "Managing Digital Transformation",
    "phase": "pre_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "L-51",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MDIO",
    "name": "Managing Diversity and Inclusion in Organizations",
    "phase": "pre_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "L-52",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "MGC",
    "name": "Managing Global Cities",
    "phase": "post_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "Amphi (East-150)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "MR",
    "name": "Managing Retailing",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "MTO",
    "name": "Managing Teams in Organizations",
    "phase": "pre_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "L-2",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 4,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MTISI4",
    "name": "Managing Technology and Information Systems for Industry 4.0",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 2,
          "start": "08:30",
          "end": "09:45"
        }
      ]
    }
  },
  {
    "code": "MDAA",
    "name": "Market Design: Applications and Analysis",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "MTCI",
    "name": "Marketing Theory and Contemporary Issues",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (East-150)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 2,
          "start": "16:15",
          "end": "17:30"
        }
      ],
      "B": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MBPC",
    "name": "Marketing to Bottom of Pyramid Consumers",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (West-100)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "MEOB",
    "name": "Methods & Evidences in Organizational Behavior",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-51",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "08:30",
          "end": "09:45"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "NPSM",
    "name": "Non-profit and Social Marketing",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-52",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "SNA",
    "name": "Social Network Analytics",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "N-22",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "SDSBA",
    "name": "Statistics for Data Science and Business Analysis",
    "phase": "post_mid",
    "credits": 1.5,
    "total_classes": 10,
    "min_pct": 80,
    "venue": "L-51",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "SDMIB",
    "name": "Strategic Decision Making in International Business",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "L-4",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "16:15",
          "end": "17:30"
        }
      ]
    }
  },
  {
    "code": "ECS",
    "name": "The Economics of Corporate Sustainability",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "Amphi (East-150)",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 5,
          "start": "16:15",
          "end": "17:30"
        }
      ]
    }
  },
  {
    "code": "ODSHEB",
    "name": "THE OPS-DRIVEN STARTUP: How Execution Builds Moats, Markets, And Momentum",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 20,
    "min_pct": 75,
    "venue": "N-22",
    "schedule_type": "dates",
    "sections": {
      "A": [
        {
          "date": "2026-09-10",
          "day": 4,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-10",
          "day": 4,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-11",
          "day": 5,
          "start": "08:30",
          "end": "10:00"
        },
        {
          "date": "2026-09-11",
          "day": 5,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-09-24",
          "day": 4,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-09-24",
          "day": 4,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-09-25",
          "day": 5,
          "start": "08:30",
          "end": "10:00"
        },
        {
          "date": "2026-09-25",
          "day": 5,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-10-29",
          "day": 4,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-10-29",
          "day": 4,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-10-30",
          "day": 5,
          "start": "08:30",
          "end": "10:00"
        },
        {
          "date": "2026-10-30",
          "day": 5,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-12",
          "day": 4,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-11-12",
          "day": 4,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-13",
          "day": 5,
          "start": "08:30",
          "end": "10:00"
        },
        {
          "date": "2026-11-13",
          "day": 5,
          "start": "10:15",
          "end": "11:45"
        },
        {
          "date": "2026-11-19",
          "day": 4,
          "start": "16:15",
          "end": "17:45"
        },
        {
          "date": "2026-11-19",
          "day": 4,
          "start": "18:00",
          "end": "19:30"
        },
        {
          "date": "2026-11-20",
          "day": 5,
          "start": "08:30",
          "end": "10:00"
        },
        {
          "date": "2026-11-20",
          "day": 5,
          "start": "10:15",
          "end": "11:45"
        }
      ]
    },
    "official_code": "OM/SM-273"
  },
  {
    "code": "ZTEST",
    "name": "Tonight Test",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 3,
    "min_pct": 75,
    "venue": "—",
    "schedule_type": "dates",
    "sections": {
      "A": [
        {
          "date": "2026-08-21",
          "day": 5,
          "start": "02:40",
          "end": "03:55"
        },
        {
          "date": "2026-08-21",
          "day": 5,
          "start": "02:55",
          "end": "04:10"
        },
        {
          "date": "2026-08-21",
          "day": 5,
          "start": "03:10",
          "end": "04:25"
        }
      ]
    }
  },
  {
    "code": "ZSAT",
    "name": "Saturday Test",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 6,
    "min_pct": 75,
    "venue": "—",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 6,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 6,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 6,
          "start": "16:15",
          "end": "17:30"
        }
      ]
    }
  },
  {
    "code": "ZSUN",
    "name": "Sunday Test",
    "phase": "full",
    "credits": 3.0,
    "total_classes": 6,
    "min_pct": 75,
    "venue": "—",
    "schedule_type": "weekly",
    "sections": {
      "A": [
        {
          "day": 7,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 7,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 7,
          "start": "16:15",
          "end": "17:30"
        }
      ]
    }
  }
];

export const IGNORED_TITLES = ['IDT'];

export function findByCode(code: string): CatalogueCourse | undefined {
  const c = code.trim().toUpperCase();
  return CATALOGUE.find((x) => x.code === c);
}

export function isIgnored(title: string): boolean {
  const t = title.trim().toUpperCase();
  return IGNORED_TITLES.some((x) => t === x || t.startsWith(x + ' ') || t.startsWith(x + '('));
}

const normalise = (s: string) =>
  s.toLowerCase().replace(/\(.*?\)/g, ' ').replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();

/** Fallback for when no code is legible: nearest catalogue name by bigram overlap. */
export function findByName(raw: string): { course?: CatalogueCourse; confidence: number } {
  const target = normalise(raw.replace(/\s*[.…]{1,3}\s*$/, ''));
  if (!target) return { confidence: 0 };

  const bigrams = (s: string) => {
    const m = new Map<string, number>();
    for (let i = 0; i < s.length - 1; i++) {
      const g = s.slice(i, i + 2);
      m.set(g, (m.get(g) ?? 0) + 1);
    }
    return m;
  };

  const A = bigrams(target);
  let best: CatalogueCourse | undefined;
  let bestScore = 0;

  for (const course of CATALOGUE) {
    const c = normalise(course.name);
    const B = bigrams(c);
    let overlap = 0;
    let total = 0;
    for (const n of A.values()) total += n;
    for (const n of B.values()) total += n;
    for (const [g, n] of A) overlap += Math.min(n, B.get(g) ?? 0);
    let score = total === 0 ? 0 : (2 * overlap) / total;
    if (c.startsWith(target) && target.length >= 10) score = Math.min(1, score + 0.35);
    if (score > bestScore) { bestScore = score; best = course; }
  }

  return bestScore >= 0.78 ? { course: best, confidence: bestScore } : { confidence: bestScore };
}
