// AUTO-GENERATED by scripts/build_catalogue.py — do not edit by hand.
// Canonical Term V course list. The image parser matches against course
// CODES from this list, which is exact-match rather than fuzzy guessing.

export interface CatalogueCourse {
  code: string;
  name: string;
  phase: 'full' | 'pre_mid' | 'post_mid';
  sections: Record<string, { day: number; start: string; end: string }[]>;
}

export const TERM = "TERM-V: AY 2026-2027";

export const CATALOGUE: CatalogueCourse[] = [
  {
    "code": "AIP",
    "name": "Analytics in Practice",
    "phase": "pre_mid",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 2,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "BM",
    "name": "Bank Management",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 3,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "BCM",
    "name": "Business Constraints Management",
    "phase": "pre_mid",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 3,
          "start": "16:15",
          "end": "17:30"
        }
      ],
      "B": [
        {
          "day": 2,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 3,
          "start": "18:00",
          "end": "19:15"
        }
      ]
    }
  },
  {
    "code": "CB",
    "name": "Consumer Behaviour",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 3,
          "start": "18:00",
          "end": "19:15"
        }
      ]
    }
  },
  {
    "code": "CCM",
    "name": "Consumption Culture & Markets",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "CRA",
    "name": "Country Risk Analysis",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 3,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "CMLS",
    "name": "Creating, Managing, and Leading Social Enterprises",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 3,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "CCBC",
    "name": "Cross Cultural Business Communication",
    "phase": "post_mid",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "DTDP",
    "name": "Design Thinking for Digital Products and Services",
    "phase": "post_mid",
    "sections": {
      "A": [
        {
          "day": 6,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 6,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 7,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 7,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "ETM",
    "name": "Economics of Talent Management",
    "phase": "post_mid",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "EVIB",
    "name": "Ethics and Values in International Business",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 3,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "FRM",
    "name": "Financial Risk Management",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 5,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 6,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 6,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "FIM",
    "name": "Fixed Income Markets",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "IASP",
    "name": "Industry Analysis, Strategy and Performance",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "ISTP",
    "name": "Inside Storytelling – Theories and Praxis for Communication and Management",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 6,
          "start": "10:15",
          "end": "11:30"
        }
      ],
      "B": [
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 6,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "IMC",
    "name": "Integrated Marketing Communication",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "IFM",
    "name": "International Financial Management",
    "phase": "pre_mid",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 3,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 4,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "LSCM",
    "name": "Logistics and Supply Chain Management",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 2,
          "start": "18:00",
          "end": "19:15"
        }
      ],
      "B": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MSO",
    "name": "Management of Self in Organisations",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 4,
          "start": "18:00",
          "end": "19:15"
        }
      ]
    }
  },
  {
    "code": "MEIP",
    "name": "Managerial Excellence: Insights from Indian Philosophy",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "MDT",
    "name": "Managing Digital Transformation",
    "phase": "pre_mid",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MDIO",
    "name": "Managing Diversity and Inclusion in Organizations",
    "phase": "pre_mid",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "MGC",
    "name": "Managing Global Cities",
    "phase": "post_mid",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "MR",
    "name": "Managing Retailing",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 5,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "MTO",
    "name": "Managing Teams in Organizations",
    "phase": "pre_mid",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 4,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MTIS",
    "name": "Managing Technology and Information Systems for Industry 4.0",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 2,
          "start": "08:30",
          "end": "09:45"
        }
      ]
    }
  },
  {
    "code": "MDAA",
    "name": "Market Design: Applications and Analysis",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "MTCI",
    "name": "Marketing Theory and Contemporary Issues",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 2,
          "start": "16:15",
          "end": "17:30"
        }
      ],
      "B": [
        {
          "day": 1,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 2,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "MBPC",
    "name": "Marketing to Bottom of Pyramid Consumers",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "MEOB",
    "name": "Methods & Evidences in Organizational Behavior",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "NPSM",
    "name": "Non-profit and Social Marketing",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "14:30",
          "end": "15:45"
        },
        {
          "day": 5,
          "start": "14:30",
          "end": "15:45"
        }
      ]
    }
  },
  {
    "code": "PD",
    "name": "Pricing Decisions",
    "phase": "post_mid",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 5,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "SDM",
    "name": "Sales and Distribution Management",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 6,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 6,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 7,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 7,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "SNA",
    "name": "Social Network Analytics",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 2,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 4,
          "start": "12:00",
          "end": "13:15"
        }
      ]
    }
  },
  {
    "code": "SDSBA",
    "name": "Statistics for Data Science and Business Analysis",
    "phase": "post_mid",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "12:00",
          "end": "13:15"
        },
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  },
  {
    "code": "SDMIB",
    "name": "Strategic Decision Making in International Business",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 1,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 4,
          "start": "16:15",
          "end": "17:30"
        }
      ]
    }
  },
  {
    "code": "TECS",
    "name": "The Economics of Corporate Sustainability",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 3,
          "start": "10:15",
          "end": "11:30"
        },
        {
          "day": 5,
          "start": "16:15",
          "end": "17:30"
        }
      ]
    }
  },
  {
    "code": "ODS",
    "name": "THE OPS-DRIVEN STARTUP: How Execution Builds Moats, Markets, And Momentum",
    "phase": "full",
    "sections": {
      "A": [
        {
          "day": 4,
          "start": "16:15",
          "end": "17:30"
        },
        {
          "day": 4,
          "start": "18:00",
          "end": "19:15"
        },
        {
          "day": 5,
          "start": "08:30",
          "end": "09:45"
        },
        {
          "day": 5,
          "start": "10:15",
          "end": "11:30"
        }
      ]
    }
  }
];

export const IGNORED_TITLES = ['IDT'];

export function findByCode(code: string): CatalogueCourse | undefined {
  const c = code.trim().toUpperCase();
  return CATALOGUE.find((x) => x.code === c);
}

export function isIgnored(title: string): boolean {
  const t = title.trim().toUpperCase();
  return IGNORED_TITLES.some((x) => t === x || t.startsWith(x + ' ') || t.startsWith(x + '('));
}

const normalise = (s: string) =>
  s.toLowerCase().replace(/\(.*?\)/g, ' ').replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();

/** Fallback for when no code is legible: nearest catalogue name by bigram overlap. */
export function findByName(raw: string): { course?: CatalogueCourse; confidence: number } {
  const target = normalise(raw.replace(/\s*[.…]{1,3}\s*$/, ''));
  if (!target) return { confidence: 0 };

  const bigrams = (s: string) => {
    const m = new Map<string, number>();
    for (let i = 0; i < s.length - 1; i++) {
      const g = s.slice(i, i + 2);
      m.set(g, (m.get(g) ?? 0) + 1);
    }
    return m;
  };

  const A = bigrams(target);
  let best: CatalogueCourse | undefined;
  let bestScore = 0;

  for (const course of CATALOGUE) {
    const c = normalise(course.name);
    const B = bigrams(c);
    let overlap = 0;
    let total = 0;
    for (const n of A.values()) total += n;
    for (const n of B.values()) total += n;
    for (const [g, n] of A) overlap += Math.min(n, B.get(g) ?? 0);
    let score = total === 0 ? 0 : (2 * overlap) / total;
    if (c.startsWith(target) && target.length >= 10) score = Math.min(1, score + 0.35);
    if (score > bestScore) { bestScore = score; best = course; }
  }

  return bestScore >= 0.78 ? { course: best, confidence: bestScore } : { confidence: bestScore };
}
